# Generated by Django 2.2.6 on 2019-11-07 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_taller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, null=True)),
                ('detalle', models.CharField(max_length=800, null=True)),
                ('estado', models.SmallIntegerField(choices=[(1, 'Inactivo'), (0, 'Activo')], default=0)),
                ('fecha_inicio', models.DateField(null=True)),
                ('fecha_culmina', models.DateField(null=True)),
                ('categoria', models.SmallIntegerField(choices=[(0, 'ARTESANIAS'), (1, 'BELLEZA'), (2, 'REPOSTERIA'), (3, 'SALUD'), (4, 'TECNOLOGIA')], default=0)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('limite', models.PositiveSmallIntegerField(blank=True, default=8, null=True)),
                ('precio', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('active', models.BooleanField(default=True)),
                ('horario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='talleres.Horario')),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.Persona')),
            ],
            managers=[
                ('active_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contador_taller', models.IntegerField(null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('add_persona', 'Can change the status of tasks')],
            },
        ),
        migrations.CreateModel(
            name='Estado_Estudiante_taller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.SmallIntegerField(choices=[(0, 'CURSANDO'), (1, 'APROBADO'), (2, 'ABANDONO')])),
                ('pago', models.SmallIntegerField(choices=[(0, 'PAGADO'), (1, 'NO CANCELADO')], default=1)),
                ('inscrito', models.DateField(auto_now_add=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estado_Estudiante_taller', to='talleres.Estudiante')),
                ('taller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estado_Estudiante_taller', to='talleres.Taller')),
            ],
            options={
                'verbose_name': 'estado estudiantil',
                'verbose_name_plural': 'Estado Estudiante',
            },
        ),
    ]
