# Generated by Django 2.1.1 on 2019-09-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='estado',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Activo'), (1, 'Inactivo')], default=0, null=True),
        ),
    ]
