# Generated by Django 2.1.1 on 2019-09-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0017_auto_20190925_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='estado',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Inactivo'), (0, 'Activo')], default=0, null=True),
        ),
    ]
