# Generated by Django 2.1.1 on 2019-10-08 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0018_auto_20190926_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['created']},
        ),
    ]
